### ISSUE TITLE
Filters not working on production build

### ISSUE THREAD

**Issue by ineptian** [scottishstoater/eleventy-web-starter#37] opened 2022-07-09 20:25 UTC
This looks like a known issue with tailwind since 3.0.12 with certain build systems.

Would be awesome if we could figure out how to fix this here. I did some poking around but couldn't quite figure out why postcss would be building those styles incorrectly. I am going to post some links from the tailwind repo that discuss the issue and some potential fixes.

https://github.com/tailwindlabs/tailwindcss/issues/5264
https://github.com/tailwindlabs/tailwindcss/discussions/7131
https://github.com/tailwindlabs/tailwindcss/discussions/7044

**Comment by chrissy-dev** [comment] 2022-07-11 09:36
Hey @ineptian, the issue is with [html-minifier](https://www.npmjs.com/package/html-minifier) and it's dependency of [clean-css](https://github.com/clean-css/clean-css) to handle minifying CSS within `<style>` tags during HTML compression. This is noted as [the culprit here](https://github.com/tailwindlabs/tailwindcss/issues/5264#issuecomment-904544499). Clean CSS does actually support this in newer versions but the version html-minifier includes is a few years old and doesn't look likely to be updated any time soon.   

There's a few options. Firstly, we want to stop html-minifier touching our CSS.

1. On line 11 in `./utils/transforms.js` set the `minifyCSS` option to `false` or remove it completely. 

If you run a build, everything should now work as expected but the inline CSS won't be minified. 

## Switch to cssnano for minifying

1. Install [cssnano](https://github.com/cssnano/cssnano) as a dependency 
```
npm install cssnano --save-dev
```

2. Update `./postcss.config.js` to inline CSS in production
```js
const isProduction = process.env.NODE_ENV === 'production';

module.exports = {
    plugins: [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
        isProduction && require('cssnano')({
            preset: 'default',
        }),
    ]
}
```

Hope this helps.

**Comment by chrissy-dev** [comment] 2022-07-25 08:32
@ineptian Closing this but feel free to comment on it to pick it up again 😊

**Closed as completed by chrissy-dev** 2022-07-25 08:32 UTC

**Comment by ineptian** [comment] 2022-07-27 19:31
@chrissy-dev thanks so much for being so on it with the replies. I installed css nano and that worked great but I actually haven't tested the filters yet since I already migrated away from using them in the meantime. I have been wanting to test this though and will report back when I have time. You can keep closed for now.
